// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package dingtalk

import (
	"github.com/kevin2027/easy-dingtalk/calendar"
	"github.com/kevin2027/easy-dingtalk/calendar/v2"
	"github.com/kevin2027/easy-dingtalk/contact"
	"github.com/kevin2027/easy-dingtalk/meeting"
	"github.com/kevin2027/easy-dingtalk/message"
	"github.com/kevin2027/easy-dingtalk/oauth2"
	"github.com/kevin2027/easy-dingtalk/utils"
)

// Injectors from wire.go:

func NewDingtalk(opt utils.DingtalkOptions) (Dingtalk, func(), error) {
	oauth2Oauth2 := oauth2.NewOuath2(opt)
	contactContact := contact.NewContact(oauth2Oauth2)
	calendar_v2Calendar := calendar_v2.NewCalendar(oauth2Oauth2)
	calendarCalendar := calendar.NewCalendar(oauth2Oauth2, contactContact)
	messageMessage := message.NewMessage(oauth2Oauth2)
	meetingMeeting := meeting.NewMeeting(oauth2Oauth2)
	dingtalk := newDingtalk(oauth2Oauth2, contactContact, calendar_v2Calendar, calendarCalendar, messageMessage, meetingMeeting)
	return dingtalk, func() {
	}, nil
}
